function MyMex(filename)
addpath(genpath(pwd));
if(nargin == 0)
	filename = 'TestStieBrockett';
end
mex('-I./', ...
'-I./BinaryFiles/', ...
'-I./CondHessian/', ...
'-I./Data/', ...
'-I./Data/k100n3ill/', ...
'-I./Data/k100n3well/', ...
'-I./Data/k30n100ill/', ...
'-I./Data/k30n100well/', ...
'-I./Data/k30n30ill/', ...
'-I./Data/k30n30illint2/', ...
'-I./Data/k3n3ill/', ...
'-I./Data/k3n3well/', ...
'-I./EGG_Classification/', ...
'-I./EGG_Classification/data/', ...
'-I./KMeansCluster/', ...
'-I./KMeansCluster/Data/', ...
'-I./KMeansCluster/KTH_TIPS2/', ...
'-I./KMeansCluster/KTH_TIPS2/KTH-TIPS2-b/', ...
'-I./KMeansCluster/KTH_TIPS2/KTH-TIPS2-b/aluminium_foil/', ...
'-I./KMeansCluster/KTH_TIPS2/KTH-TIPS2-b/brown_bread/', ...
'-I./KMeansCluster/KTH_TIPS2/KTH-TIPS2-b/corduroy/', ...
'-I./KMeansCluster/KTH_TIPS2/KTH-TIPS2-b/cork/', ...
'-I./KMeansCluster/KTH_TIPS2/KTH-TIPS2-b/cotton/', ...
'-I./KMeansCluster/KTH_TIPS2/KTH-TIPS2-b/cracker/', ...
'-I./KMeansCluster/KTH_TIPS2/KTH-TIPS2-b/lettuce_leaf/', ...
'-I./KMeansCluster/KTH_TIPS2/KTH-TIPS2-b/linen/', ...
'-I./KMeansCluster/KTH_TIPS2/KTH-TIPS2-b/white_bread/', ...
'-I./KMeansCluster/KTH_TIPS2/KTH-TIPS2-b/wood/', ...
'-I./KMeansCluster/KTH_TIPS2/KTH-TIPS2-b/wool/', ...
'-I./KMeansCluster/Keck/', ...
'-I./KMeansCluster/Virus/', ...
'-I./KMeansCluster/brodatz/', ...
'-I./KMeansCluster/spd-dpmm/', ...
'-I./LDOneParamL1Results/', ...
'-I./LDOneParamL1Results/k100n100_ball/', ...
'-I./LDOneParamL1Results/k100n100_ball_ill/', ...
'-I./LDOneParamL1Results/k100n100_cluster/', ...
'-I./LDOneParamL1Results/k100n100_outlier/', ...
'-I./LDOneParamL1Results/k100n100_outlier_well/', ...
'-I./LDOneParamL1Results/k100n3_ball/', ...
'-I./LDOneParamL1Results/k100n3_ball_ew/', ...
'-I./LDOneParamL1Results/k100n3_ball_ill/', ...
'-I./LDOneParamL1Results/k100n3_cluster/', ...
'-I./LDOneParamL1Results/k100n3_outlier/', ...
'-I./LDOneParamL1Results/k100n3_outlier_well/', ...
'-I./LDOneParamLinftyResults/', ...
'-I./LDOneParamLinftyResults/k100n3_ball/', ...
'-I./LDOneParamLinftyResults/k100n3_ball_ill/', ...
'-I./LDOneParamLinftyResults/k100n3_cluster/', ...
'-I./LDOneParamLinftyResults/k100n3_outlier/', ...
'-I./LDOneParamLinftyResults/k100n3_outlier_well/', ...
'-I./LDOneParamLinftyResults_v0/', ...
'-I./LDOneParamLinftyResults_v0/LDOneParam_k100n10_ball/', ...
'-I./LDOneParamLinftyResults_v0/LDOneParam_k100n10_cluster/', ...
'-I./LDOneParamLinftyResults_v0/LDOneParam_k100n10_equal/', ...
'-I./LDOneParamLinftyResults_v0/LDOneParam_k100n3_ball/', ...
'-I./LDOneParamLinftyResults_v0/LDOneParam_k100n3_ball_small/', ...
'-I./LDOneParamLinftyResults_v0/LDOneParam_k100n3_cluster/', ...
'-I./LDOneParamLinftyResults_v0/LDOneParam_k100n3_equal/', ...
'-I./Manifolds/', ...
'-I./Manifolds/CpxNStQOrth/', ...
'-I./Manifolds/ElasticShape/', ...
'-I./Manifolds/EucPositive/', ...
'-I./Manifolds/Euclidean/', ...
'-I./Manifolds/Grassmann/', ...
'-I./Manifolds/L2Sphere/', ...
'-I./Manifolds/LowRank/', ...
'-I./Manifolds/Oblique/', ...
'-I./Manifolds/OrthGroup/', ...
'-I./Manifolds/PreShapeCurves/', ...
'-I./Manifolds/SPDEucManifold/', ...
'-I./Manifolds/SPDManifold/', ...
'-I./Manifolds/SPDTensor/', ...
'-I./Manifolds/Sphere/', ...
'-I./Manifolds/SphereTx/', ...
'-I./Manifolds/Stiefel/', ...
'-I./NewResult/', ...
'-I./NewResult/k100n100well0/', ...
'-I./NewResult/k100n100well05/', ...
'-I./NewResult/k100n100well09/', ...
'-I./NewResult/k100n100welln05/', ...
'-I./NewResult/k100n100welln09/', ...
'-I./NewResult/k100n3well_TestData/', ...
'-I./NewResult/k3n3well/', ...
'-I./OneParamResultRI/', ...
'-I./OneParamResultRandomInt/', ...
'-I./Others/', ...
'-I./Others/SparseBLAS/', ...
'-I./Others/fftw/', ...
'-I./Problems/', ...
'-I./Problems/ElasticCurvesRO/', ...
'-I./Problems/EucFrechetMean/', ...
'-I./Problems/EucPosSpCd/', ...
'-I./Problems/EucQuadratic/', ...
'-I./Problems/GrassRQ/', ...
'-I./Problems/KarcherMean/', ...
'-I./Problems/LRMatrixCompletion/', ...
'-I./Problems/ObliqueSparsePCA/', ...
'-I./Problems/ObliqueTestSparsePCA/', ...
'-I./Problems/OrthBoundingBox/', ...
'-I./Problems/PreShapePathStraighten/', ...
'-I./Problems/SPDEucMean/', ...
'-I./Problems/SPDMean/', ...
'-I./Problems/SPDMeanL1/', ...
'-I./Problems/SPDMeanLDOneParam/', ...
'-I./Problems/SPDMeanLDOneParamL1/', ...
'-I./Problems/SPDMeanLDOneParamLinfty/', ...
'-I./Problems/SPDMeanLinfty/', ...
'-I./Problems/SPDMeanStein/', ...
'-I./Problems/SPDMeanSteinV2/', ...
'-I./Problems/SPDMeanSymmLDOneParam/', ...
'-I./Problems/SPDMeanSymmLDOneParamL1/', ...
'-I./Problems/SPDMeanSymmLDOneParamLinfty/', ...
'-I./Problems/SPDTensorDL/', ...
'-I./Problems/ShapePathStraighten/', ...
'-I./Problems/SphereConvexHull/', ...
'-I./Problems/SphereHessianStein/', ...
'-I./Problems/SphereHessianSteinMax/', ...
'-I./Problems/SphereHessianSteinMin/', ...
'-I./Problems/SphereTxRQ/', ...
'-I./Problems/StieBrockett/', ...
'-I./Problems/StieSoftICA/', ...
'-I./Problems/StieSparseBrockett/', ...
'-I./Problems/StieSumBrockett/', ...
'-I./Problems/WeightedLowrank/', ...
'-I./PropsStepVSEig/', ...
'-I./PropsStepVSEig/BBStepVsEigenvalues/', ...
'-I./PropsStepVSEig/a05AH/', ...
'-I./PropsStepVSEig/a05Ar/', ...
'-I./PropsStepVSEig/a05rand/', ...
'-I./PropsStepVSEig/a0AH/', ...
'-I./PropsStepVSEig/a0Ar/', ...
'-I./PropsStepVSEig/a0rand/', ...
'-I./PropsStepVSEig/an05AH/', ...
'-I./PropsStepVSEig/an05Ar/', ...
'-I./PropsStepVSEig/an05rand/', ...
'-I./Results/', ...
'-I./Results/L1Results/', ...
'-I./Results/L1Results/k100n100_ball/', ...
'-I./Results/L1Results/k100n100_ball_ill/', ...
'-I./Results/L1Results/k100n100_outlier/', ...
'-I./Results/L1Results/k100n100_outlier_well/', ...
'-I./Results/L1Results/k100n3_ball/', ...
'-I./Results/L1Results/k100n3_ball_ill/', ...
'-I./Results/L1Results/k100n3_cluster/', ...
'-I./Results/L1Results/k100n3_outlier_initial/', ...
'-I./Results/L1Results/k100n3_outlier_well/', ...
'-I./Results/L1Results/k100n3_outlier_well_initial/', ...
'-I./Results/L2Results/', ...
'-I./Results/L2Results/Data_Save_for_Paper/', ...
'-I./Results/L2Results/Data_Save_for_Paper/k100n3ill/', ...
'-I./Results/L2Results/Data_Save_for_Paper/k100n3well/', ...
'-I./Results/L2Results/Data_Save_for_Paper/k30n100ill/', ...
'-I./Results/L2Results/Data_Save_for_Paper/k30n100well/', ...
'-I./Results/L2Results/Data_Save_for_Paper/k30n30ill/', ...
'-I./Results/L2Results/Data_Save_for_Paper/k30n30illint2/', ...
'-I./Results/L2Results/Data_Save_for_Paper/k30n30illratio/', ...
'-I./Results/L2Results/Data_Save_for_Paper/k3n3ill/', ...
'-I./Results/L2Results/Data_Save_for_Paper/k3n3ill0402/', ...
'-I./Results/L2Results/Data_Save_for_Paper/k3n3well/', ...
'-I./Results/L2Results/k100n3ill/', ...
'-I./Results/L2Results/k100n3well/', ...
'-I./Results/L2Results/k30n100ill/', ...
'-I./Results/L2Results/k30n100well/', ...
'-I./Results/L2Results/k30n30ill/', ...
'-I./Results/L2Results/k30n30illint2/', ...
'-I./Results/L2Results/k30n30illratio/', ...
'-I./Results/L2Results/k3n3ill/', ...
'-I./Results/L2Results/k3n3ill0402/', ...
'-I./Results/L2Results/k3n3well/', ...
'-I./Results/LinftyResults/', ...
'-I./Results/LinftyResults/k100n100_ball/', ...
'-I./Results/LinftyResults/k100n100_ball_ill/', ...
'-I./Results/LinftyResults/k100n100_cluster/', ...
'-I./Results/LinftyResults/k100n100_outlier/', ...
'-I./Results/LinftyResults/k100n100_outlier_well/', ...
'-I./Results/LinftyResults/k100n3_ball/', ...
'-I./Results/LinftyResults/k100n3_ball_ill/', ...
'-I./Results/LinftyResults/k100n3_cluster/', ...
'-I./Results/LinftyResults/k100n3_outlier/', ...
'-I./Results/LinftyResults/k100n3_outlier_well/', ...
'-I./SPDMean/', ...
'-I./SPDMeanMetricComparison/', ...
'-I./SPDMeanMetricComparison/k100n3metric/', ...
'-I./SPDMeanMetricComparison/k30n100metric/', ...
'-I./SPDMeanMetricComparison/k3n3metric/', ...
'-I./SPDMeanTest/', ...
'-I./Solvers/', ...
'-I./SymmLDOneParamLinftyResults/', ...
'-I./SymmLDOneParamLinftyResults/SymmLDOneParam_k100n3_ball/', ...
'-I./SymmLDOneParamLinftyResults/SymmLDOneParam_k100n3_ball_small/', ...
'-I./SymmLDOneParamLinftyResults/SymmLDOneParam_k100n3_cluster/', ...
'-I./SymmLDOneParamLinftyResults/SymmLDOneParam_k100n3_equal/', ...
'-I./TestPipe/', ...
'-I./TestPipe/L1/', ...
'-I./TestPipe/L2/', ...
'-I./TestPipe/Linfty/', ...
'-I./average/', ...
'-I./cwrapper/', ...
'-I./cwrapper/blas/', ...
'-I./cwrapper/lapack/', ...
'-I./test/', ...
['./test/' filename '.cpp'], ...
'./Manifolds/Element.cpp', './Manifolds/LinearOPE.cpp', './Manifolds/Manifold.cpp', './Manifolds/ProductElement.cpp', './Manifolds/ProductManifold.cpp', './Manifolds/SharedSpace.cpp', './Manifolds/SmartSpace.cpp', ...
'./Manifolds/CpxNStQOrth/CSOVariable.cpp', './Manifolds/CpxNStQOrth/CSOVector.cpp', './Manifolds/CpxNStQOrth/CpxNStQOrth.cpp', ...
'./Manifolds/ElasticShape/ElasticShape.cpp', './Manifolds/ElasticShape/ShapeVariable.cpp', './Manifolds/ElasticShape/ShapeVector.cpp', ...
'./Manifolds/EucPositive/EucPosVariable.cpp', './Manifolds/EucPositive/EucPosVector.cpp', './Manifolds/EucPositive/EucPositive.cpp', ...
'./Manifolds/Euclidean/EucVariable.cpp', './Manifolds/Euclidean/EucVector.cpp', './Manifolds/Euclidean/Euclidean.cpp', ...
'./Manifolds/Grassmann/GrassVariable.cpp', './Manifolds/Grassmann/GrassVector.cpp', './Manifolds/Grassmann/Grassmann.cpp', ...
'./Manifolds/L2Sphere/L2Sphere.cpp', './Manifolds/L2Sphere/L2SphereVariable.cpp', './Manifolds/L2Sphere/L2SphereVector.cpp', ...
'./Manifolds/LowRank/LowRank.cpp', './Manifolds/LowRank/LowRankVariable.cpp', './Manifolds/LowRank/LowRankVector.cpp', ...
'./Manifolds/Oblique/Oblique.cpp', './Manifolds/Oblique/ObliqueVariable.cpp', './Manifolds/Oblique/ObliqueVector.cpp', ...
'./Manifolds/OrthGroup/OrthGroup.cpp', './Manifolds/OrthGroup/OrthGroupVariable.cpp', './Manifolds/OrthGroup/OrthGroupVector.cpp', ...
'./Manifolds/PreShapeCurves/PSCVariable.cpp', './Manifolds/PreShapeCurves/PSCVector.cpp', './Manifolds/PreShapeCurves/PreShapeCurves.cpp', ...
'./Manifolds/SPDEucManifold/SPDEucManifold.cpp', './Manifolds/SPDEucManifold/SPDEucVariable.cpp', './Manifolds/SPDEucManifold/SPDEucVector.cpp', ...
'./Manifolds/SPDManifold/SPDManifold.cpp', './Manifolds/SPDManifold/SPDVariable.cpp', './Manifolds/SPDManifold/SPDVector.cpp', ...
'./Manifolds/SPDTensor/SPDTVariable.cpp', './Manifolds/SPDTensor/SPDTVector.cpp', './Manifolds/SPDTensor/SPDTensor.cpp', ...
'./Manifolds/Sphere/Sphere.cpp', './Manifolds/Sphere/SphereVariable.cpp', './Manifolds/Sphere/SphereVector.cpp', ...
'./Manifolds/SphereTx/SphereTx.cpp', ...
'./Manifolds/Stiefel/StieVariable.cpp', './Manifolds/Stiefel/StieVector.cpp', './Manifolds/Stiefel/Stiefel.cpp', ...
'./Others/ForDebug.cpp', './Others/MinPNormConHull.cpp', './Others/MyMatrix.cpp', './Others/Spline.cpp', './Others/Timer.cpp', './Others/randgen.cpp', ...
'./Others/SparseBLAS/nist_spblas.cpp', ...
'./Problems/Problem.cpp', './Problems/juliaProblem.cpp', './Problems/mexProblem.cpp', ...
'./Problems/ElasticCurvesRO/DriverElasticCurvesRO.cpp', './Problems/ElasticCurvesRO/ElasticCurvesRO.cpp', ...
'./Problems/EucFrechetMean/EucFrechetMean.cpp', ...
'./Problems/EucPosSpCd/EucPosSpCd.cpp', ...
'./Problems/EucQuadratic/EucQuadratic.cpp', ...
'./Problems/GrassRQ/GrassRQ.cpp', ...
'./Problems/KarcherMean/KarcherMean.cpp', ...
'./Problems/LRMatrixCompletion/LRMatrixCompletion.cpp', ...
'./Problems/ObliqueSparsePCA/ObliqueSparsePCA.cpp', ...
'./Problems/ObliqueTestSparsePCA/ObliqueTestSparsePCA.cpp', ...
'./Problems/OrthBoundingBox/OrthBoundingBox.cpp', ...
'./Problems/PreShapePathStraighten/PreShapePathStraighten.cpp', ...
'./Problems/SPDEucMean/SPDEucMean.cpp', ...
'./Problems/SPDMean/SPDMean.cpp', ...
'./Problems/SPDMeanL1/SPDMeanL1.cpp', ...
'./Problems/SPDMeanLDOneParam/SPDMeanLDOneParam.cpp', ...
'./Problems/SPDMeanLDOneParamL1/SPDMeanLDOneParamL1.cpp', ...
'./Problems/SPDMeanLDOneParamLinfty/SPDMeanLDOneParamLinfty.cpp', ...
'./Problems/SPDMeanLinfty/SPDMeanLinfty.cpp', ...
'./Problems/SPDMeanStein/SPDMeanStein.cpp', ...
'./Problems/SPDMeanSteinV2/SPDMeanSteinV2.cpp', ...
'./Problems/SPDMeanSymmLDOneParam/SPDMeanSymmLDOneParam.cpp', ...
'./Problems/SPDMeanSymmLDOneParamL1/SPDMeanSymmLDOneParamL1.cpp', ...
'./Problems/SPDMeanSymmLDOneParamLinfty/SPDMeanSymmLDOneParamLinfty.cpp', ...
'./Problems/SPDTensorDL/SPDTensorDL.cpp', ...
'./Problems/ShapePathStraighten/ShapePathStraighten.cpp', ...
'./Problems/SphereConvexHull/SphereConvexHull.cpp', ...
'./Problems/SphereHessianStein/SphereHessianStein.cpp', ...
'./Problems/SphereHessianSteinMax/SphereHessianSteinMax.cpp', ...
'./Problems/SphereHessianSteinMin/SphereHessianSteinMin.cpp', ...
'./Problems/SphereTxRQ/SphereTxRQ.cpp', ...
'./Problems/StieBrockett/StieBrockett.cpp', ...
'./Problems/StieSoftICA/StieSoftICA.cpp', ...
'./Problems/StieSparseBrockett/StieSparseBrockett.cpp', ...
'./Problems/StieSumBrockett/StieSumBrockett.cpp', ...
'./Problems/WeightedLowrank/WeightedLowRank.cpp', ...
'./Solvers/LRBFGS.cpp', './Solvers/LRBFGSLPSub.cpp', './Solvers/LRTRSR1.cpp', './Solvers/MRankAdaptive.cpp', './Solvers/QuasiNewton.cpp', './Solvers/RBFGS.cpp', './Solvers/RBFGSLPSub.cpp', './Solvers/RBroydenFamily.cpp', './Solvers/RCG.cpp', './Solvers/RGS.cpp', './Solvers/RNewton.cpp', './Solvers/RSD.cpp', './Solvers/RTRNewton.cpp', './Solvers/RTRSD.cpp', './Solvers/RTRSR1.cpp', './Solvers/RWRBFGS.cpp', './Solvers/Solvers.cpp', './Solvers/SolversLS.cpp', './Solvers/SolversLSLPSub.cpp', './Solvers/SolversTR.cpp', ...
['-D' upper(filename)], '-L.\BinaryFiles\', '-lmwblas', '-lmwlapack', '-largeArrayDims', '-output', ['./BinaryFiles/' filename ]);
end